#!/bin/bash

msg () {
    for msgline
    do echo "$pn: $msgline" >&2
    done
}

fatal () { msg "$@" ; usage ; exit 1 ; }

finish () {
    [[ $debug -eq 1 ]] && cp -a $td "$launchdir"/
    rm -rf $td
    cd "$launchdir"
    exit
}

tempdir () {
    : ${TMPDIR:="/tmp"}
    tdbase=$TMPDIR/$USER
    test -e $tdbase || mkdir -p $tdbase
    td=$(mktemp -d $tdbase/$(basename $0).XXXXXX) || fatal "Could not create temp dir in $tdbase"
    echo $td
}

set -e   # Terminate script at first error
